meta_product_name: "Core Studio Grenoble"
meta_title: "Core Studio Grenoble - Réservation de cours yoga, fitness et pilates en ligne"
meta_description: "Résevation et achat de crédits en ligne pour les cours de yoga, pilates, coaching privés de fitness Core Studio à Grenoble"
meta_image: "cover.png" # should exist in `app/assets/images/`
